'use client';

import { useState } from 'react';

type Props = { eventTypeSlug: string; adultCount: number; childCount: number; eventDate: string; addonSlugs: string[]; deposit: number };

export function ReservationPanel({ eventTypeSlug, adultCount, childCount, eventDate, addonSlugs, deposit }: Props) {
  const [method, setMethod] = useState<'transfer' | 'card'>('transfer'); const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [email, setEmail] = useState(''); const [result, setResult] = useState<{ reference: string; depositAmount: number } | null>(null); const [error, setError] = useState('');
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); const response = await fetch('/api/orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ customerName: name, customerPhone: phone, customerEmail: email, adultCount, childCount, eventDate, eventTypeSlug, addonSlugs, paymentMethod: method }) }); if (!response.ok) { setError('Revisa tus datos e inténtalo nuevamente.'); return; } setResult(await response.json()); }
  if (result) return <div className="transfer-details"><p>Reserva registrada: <b>{result.reference}</b></p>{method === 'transfer' ? <><p>Transfiere la seña de <b>{new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(result.depositAmount)}</b>.</p><span><b>CBU</b><code>0000003100031585235581</code></span><span><b>Titular</b><em>Luis Oscar Martínez</em></span><small>Envía el comprobante por WhatsApp para confirmar la reserva.</small></> : <p>Recibimos tu solicitud. El equipo se comunicará contigo para completar el pago con tarjeta.</p>}</div>;
  return <form className="reservation-form" onSubmit={submit}><p>Completa tus datos para reservar con una seña de <b>{new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(deposit)}</b>.</p><div className="payment-methods"><button type="button" className={method === 'transfer' ? 'selected' : ''} onClick={() => setMethod('transfer')}>Transferencia</button><button type="button" className={method === 'card' ? 'selected' : ''} onClick={() => setMethod('card')}>Tarjeta</button></div><label>Nombre completo<input required value={name} onChange={event => setName(event.target.value)} /></label><label>Teléfono<input required type="tel" value={phone} onChange={event => setPhone(event.target.value)} /></label><label>Email<input required type="email" value={email} onChange={event => setEmail(event.target.value)} /></label>{error && <small>{error}</small>}<button type="submit">Continuar con la seña</button></form>;
}
